---
functional:
  - Пользователи должны иметь возможность соревноваться друг с другом в решении задач на скорость
  - Пользователи должны видеть код друг друга.
  - Пользователи должны иметь возможность начисления очков для рейтинга.
  - Пользователь должен иметь возможность проведения игры с ботом.
  - Пользователи должны иметь возможность проведения игры с другом по ссылке.
  - Пользователь должен иметь возможность менять язык программирования во время решения.
  - Пользователь должен иметь возможность выбрать уровень сложности игры.
  - Пользователь должен иметь возможность видеть задачи на русском и английском языках.
  - Пользователи не принимающие участие в игре должны иметь возможность следить за ходом игры.
  - Авторизованные пользователи должны иметь возможность общаться в чате.
  - Пользователи должны иметь доступ к завершенным играм в записи.
  - Пользователь должен иметь возможность зарегистрироваться с помощью учётной записи Github и Discord.
  - Пользователь должен иметь возможность востанавливать акаунт в случае потери пароля.
  - Пользователь должен иметь возможность проводить игру со случайным игроком.
  - Пользователь должен иметь возможность выбирать время игры и тип игры - закрытый или открытый.
  - Пользователь должен иметь возможность писать сопернику в чате во время игры.
  - В случае победы или проигрыша должен вспылавть банер с оповещением о победе или проигрыше.
  - Вначале первой игры у пользователя должна быть возможность посмотреть подробную инстукцию.
  - Пользователь должен иметь возможность смотреть рейтинги игроков.
  - Пользователь должен иметь возможность отказаться от приглашения в игру.
  - Пользователь должен иметь возможность отменить своё приглашение.
  - Пользователь должен иметь возможность посмотреть кто из дургих пользователей сейчас онлайн.

non-functional:
  - Сайт должен быть разработан с учетом удобства использования. 
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен содержать удобный редактор кода.
  - Сайт должен быть оптимизирован для мобильных устройств. 
  - Сайт должен присылать уведомления пользователю о вызове от другого пользователя.
  - Сайт должен быть совместимым с разными браузерами (Chrome 108-текущий, Firefox 108-текущий, Microsoft Edge 108-текущий, Opera 94–текущий, Бледная луна 31.4.3-текущий, Safari 16.3–текущий, Vivaldi 5.7–текущий, Arc 1.10-текущий).
  - Сайт должен показывать рейтиг пользователей игры.
  - Сайт должен быть способен обрабатывать большое количество трафика(более 1000 пользователей одновременно).
  - Сайт должен иметь совместимость со всеми операционными системами (Windows 10, macOS Catalina 10.15.1, Linux Mint 21.2 "Victoria", Fedora Linux 37)
  - Сайт должен показывать текущую версию игры.

implicit:
  - Возможность регистрации.
  - Возможность авторизации.
  - Возможность регистрации и авторизации с разных устройств.
  - Проект codebattle должен иметь открытый код. 
  - Сайт должен предлагать принять куки.
  - Сайт должен иметь функцию смены на ночную тему.
  - При регистрации сайт должен проверить пользователя капчей и убедиться, что он не бот.
  - Пользователь должен иметь возможность загрузить свой аватар на сайте.
  - Встроенная система модерации в чате для автоудаления рекламы, ненормативной лексики, и призывам к сомнительным действиям.